name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint
      - name: Typecheck
        run: bun run test:types
      - name: Build
        run: bun run build
      - name: Unit tests
        run: bun run test:unit
      - name: Publish
        if: github.event_name == 'pull_request'
        run: bun x pkg-pr-new publish './packages/*' --template './examples/*'
      # TODO: upload coverage
      # - name: Upload coverage
