name: Release

on:
  push:
    branches: [main]
  pull_request:
    types: ["closed"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  pages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'maxmorozoff/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        if: github.event.pull_request.merged != true
        with:
          version: bun run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        id: build
        if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'changeset-release/main')
        run: bun run build
      - name: Publish to npm
        id: publish
        uses: changesets/action@v1
        if: steps.build.outcome == 'success'
        with:
          publish: bun publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
